#!/bin/bash

ETC=/etc/spork
WEB=/var/www/html/spork
PREVIEW=FALSE
SCRIPTDIR=`dirname $0`

while [ "$1" != "" ]
do
  case "$1" in
    -preview)
      PREVIEW=TRUE
      ;;
    *)
      echo Unrecognized parameter: $1
      exit
      ;;
  esac
  shift
done

cd $SCRIPTDIR/etc

LIST=""
for FILE in *
do
  if [ "$FILE" != "spork.conf" ]
  then
    if [ -e "$ETC/$FILE" ]
    then
      CKSUM1=`cksum $FILE | cut -d " " -f1`
      CKSUM2=`cksum $ETC/$FILE | cut -d " " -f1`

      if [ "$CKSUM1" != "$CKSUM2" ]
      then
        LIST="$LIST $FILE"
      fi
    else
      LIST="$LIST $FILE"
    fi
  fi
done

for FILE in $LIST
do
  if [ "$PREVIEW" = "TRUE" ]
  then
    echo cp $FILE $ETC
  else
    cp $FILE $ETC
  fi
done

cd ../web

LIST=""
for FILE in *
do
  if [ -e "$WEB/$FILE" ]
  then
    CKSUM1=`cksum $FILE | cut -d " " -f1`
    CKSUM2=`cksum $WEB/$FILE | cut -d " " -f1`

    if [ "$CKSUM1" != "$CKSUM2" ]
    then
      LIST="$LIST $FILE"
    fi
  else
    LIST="$LIST $FILE"
  fi
done

for FILE in $LIST
do
  if [ "$PREVIEW" = "TRUE" ]
  then
    echo cp $FILE $WEB
  else
    cp $FILE $WEB
  fi
done

