#!/bin/bash

while [ "$1" != "" ]
do
  case "$1" in
    -n|--name)
      shift
      APPNAME="$1"
      ;;
    *)
      echo "Unrecognized argument: $1"
      echo "Usage:"
      echo "  $0 [--name <name>]"
      exit
      ;;
  esac
  shift
done

if [ "$APPNAME" = "" ]
then
  read -p "App Name: " APPNAME
fi

php $0.php "$APPNAME"

