#!/bin/bash

while [ "$1" != "" ]
do
  case "$1" in
    -a|--app)
      shift
      APPID="$1"
      ;;
    -n|--name)
      shift
      COLLNAME="$1"
      ;;
    *)
      echo "Unrecognized argument: $1"
      echo "Usage:"
      echo "  $0 [--app <id>] [--name <name>]"
      exit
      ;;
  esac
  shift
done

if [ "$APPID" = "" ]
then
  read -p "App ID: " APPID
fi

if [ "$COLLNAME" = "" ]
then
  read -p "Collection Name: " COLLNAME
fi

php $0.php "$APPID" "$COLLNAME"

